spring:
  datasource:
    url: ${SPRING_BOOT_URL}
    username: ${SPRING_BOOT_USERNAME}
    password: ${SPRING_BOOT_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework: DEBUG
    ru.levelup.app: DEBUG
  file:
    name: logs.log