spring:
  datasource:
    url: ${SPRING_BOOT_URL}
    username: ${SPRING_BOOT_USERNAME}
    password: ${SPRING_BOOT_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
