spring:
  datasource:
    url: ${SPRING_BOOT_URL}
    username: ${SPRING_BOOT_USERNAME}
    password: ${SPRING_BOOT_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
